data_plant = [
	{
		"customer" : "LGP",
		"type" : "908",
		"material_no" : "LGP908-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 0.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "M",
		"fg_qty" : 0.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 1.1
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066102LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "E",
		"fg_qty" : 194.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 1.2
	},
	{
		"customer" : "LGP",
		"type" : "01R",
		"material_no" : "LGP01R-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "E",
		"fg_qty" : 0.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 1.3
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066103LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 8.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 2.0
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066105CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 3.0
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066101LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 6.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 4.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210662LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 12.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 5.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210663LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 6.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210664LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 4.0,
		"z_start_date" : "1900-01-01",
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : 0.0,
		"plant" : "SVI2",
		"seq_no" : 7.0
	}
]


data_sale = [{
		"customer" : "LGP",
		"type" : "908",
		"material_no" : "LGP908-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : "0212188692",
		"so_item" : "000012",
		"so_qty" : 1.0,
		"so_workweek" : "2024-32",
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 0.0
	},
	{
		"customer" : "LGP",
		"type" : "908",
		"material_no" : "LGP908-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : "0212188692",
		"so_item" : "000011",
		"so_qty" : 1.0,
		"so_workweek" : "2024-32",
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 0.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "M",
		"fg_qty" : 0.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 1.1
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066102LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "E",
		"fg_qty" : 194.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 1.2
	},
	{
		"customer" : "LGP",
		"type" : "01R",
		"material_no" : "LGP01R-210661CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "E",
		"fg_qty" : 0.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 1.3
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066103LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 8.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 2.0
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066105CLF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 3.0
	},
	{
		"customer" : "LGP",
		"type" : "01P",
		"material_no" : "LGP01P-21066101LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 6.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 4.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210662LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 12.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 5.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210663LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 0.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 6.0
	},
	{
		"customer" : "LGP",
		"type" : "01E",
		"material_no" : "LGP01E-210664LF",
		"fg_material_no" : "LGP908-210661CLF",
		"so" : None,
		"so_item" : None,
		"so_qty" : None,
		"so_workweek" : None,
		"status" : 10,
		"m_group" : "F",
		"fg_qty" : 4.0,
		"z_start_date" : None,
		"z_prod_order" : None,
		"z_plan_order" : None,
		"z_orignal_qty" : None,
		"plant" : "SVI2",
		"seq_no" : 7.0
	}
]